import fixHeight from './includes/fixHeight.js';
import mobileNav from './includes/mobileNav.js';
import modal from './includes/modal.js';
import bannerSlider from './includes/bannerSlider.js';
import subscribeFormValidation from './includes/subscribeFormValidation.js';
import photoSwipe from './includes/photoSwipe.js';
import loadMore from './includes/loadMore.js';
import tabs from './includes/tabs.js';
import dataToggle from './includes/dataToggle.js';
import dataTrigger from './includes/dataTrigger.js';
import catalog from './includes/catalog.js';
import footerMenu from './includes/footerMenu.js';
import categoriesSlider from './includes/categoriesSlider.js';
import productsSlider from './includes/productsSlider.js';
import brandsSlider from './includes/brandsSlider.js';
import select from './includes/select.js';
import filter from './includes/filter.js';
import gallery from './includes/gallery.js';
import phoneInput from './includes/phoneInput.js';
import contactsFormValidation from './includes/contactsFormValidation.js';
import aboutSlider from './includes/aboutSlider.js';
import showPassword from './includes/showPassword.js';
import closeAlert from './includes/closeAlert.js';
import orderFormValidation from './includes/orderFormValidation.js';
import enterCode from './includes/enterCode.js';
import loginFormValidation from './includes/loginFormValidation.js';
import compareSlider from './includes/compareSlider.js';
import feedbackFormValidation from './includes/feedbackFormValidation.js';
import daysCountdown from './includes/daysCountdown.js';
import timeCountdown from './includes/timeCountdown.js';
import numbersInput from './includes/numbersInput.js';
import customerRadio from './includes/customerRadio.js';
import deliverySelect from './includes/deliverySelect.js';
import '../sass/main.sass';



fixHeight();
mobileNav();
modal();
photoSwipe();
tabs();
dataToggle();
dataTrigger();
catalog();
footerMenu();
bannerSlider();
categoriesSlider();
productsSlider();
brandsSlider();
loadMore();
select();
filter();
gallery();
phoneInput();
aboutSlider();
showPassword();
closeAlert();
enterCode();
compareSlider();
daysCountdown();
timeCountdown();
numbersInput();
customerRadio();
deliverySelect();
loginFormValidation();
feedbackFormValidation();
subscribeFormValidation();
contactsFormValidation();
orderFormValidation();
